language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - go version
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd -f /dev/null
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
