name: "Proof::helm"
on:
  push:
    branches:
      - "master"
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t artipie
      - name: Start helm example and proof it works
        run: |
          cd examples/helm
          sed -i 's+artipie/artipie:latest+artipie+' run.sh
          ./run.sh