name: "Proof::binary"
"on": [push]
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t artipie
      - name: Start binrary example and proof it works
        run: |
          cd examples/binary
          sed -i 's+artipie/artipie:latest+artipie+' run.sh
          ./run.sh