name: "Proof::nuget"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t artipie
      - name: Repalce docker image with locally built one
        run: |
          cd examples/nuget
          sed -i 's+artipie/artipie:latest+artipie+' run.ps1
      - name: Start nuget example and proof it works
        run: |
          Set-Location examples/nuget
          .\run.ps1
        shell: pwsh